name: Verify

on: [ push ]

env:
  LEFTHOOK: 0

jobs:

  verify:
    name: 🔎 Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: meza/action-setup-node-pnpm@main
        with:
          node-version: latest
          cache-name: pure-dependencies
      - run: pnpm ci
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          junit_files: "reports/junit.xml"
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: always()
        with:
          format: markdown
          output: file
          hide_complexity: false
          badge: true
          filename: "reports/coverage/cobertura-coverage.xml"
      - name: Publish code coverage report
        if: always()
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      - run: npx semantic-release --dry-run
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
      new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}
